$engine: 3
$onesync: on
name: Ricis Dev Server
description: Recipe for Ricis custom FiveM server.

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  # Download Ricis Dev Server
  - action: download_github
    src: https://github.com/ricizockt/ricis_dev_server
    ref: main
    subpath: resources
    dest: ./resources/ricis_dev_server

  # Download server.cfg for Ricis Dev Server
  - action: download_file
    url: https://github.com/RiCIcom/ricis_dev_server/blob/main/server.cfg
    path: ./server.cfg
