$engine: 3
$onesync: on
name: Ricis Dev Server
description: Recipe for Ricis custom FiveM server.

variables:
  - name: serverName
    description: "Enter the server name"
    default: "Ricis Dev Server"
  
  - name: dbHost
    description: "Enter the database host (e.g., localhost)"
    default: "localhost"
  
  - name: dbName
    description: "Enter the database name"
    default: "fivem"
  
  - name: dbUsername
    description: "Enter the database username"
    default: "root"
  
  - name: dbPassword
    description: "Enter the database password"
    default: ""
  
  - name: maxClients
    description: "Enter the maximum number of clients"
    default: "32"
  
  - name: svLicense
    description: "Enter your server license key"
    default: ""

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Download Ricis Dev Server
  - action: download_github
    src: https://github.com/ricicom/ricis_dev_server
    ref: main
    subpath: resources
    dest: ./resources/ricis_dev_server

  # Download server_template.cfg for Ricis Dev Server
  - action: download_file
    url: https://raw.githubusercontent.com/ricicom/ricis_dev_server/main/server.cfg
    path: ./tmp/recipe/server.cfg

  # Download logo.png for Ricis Dev Server
  - action: download_file
    url: https://raw.githubusercontent.com/ricicom/ricis_dev_server/main/logo.png
    path: ./tmp/recipe/logo.png

  # Download banner.png for Ricis Dev Server
  - action: download_file
    url: https://raw.githubusercontent.com/ricicom/ricis_dev_server/main/banner.png
    path: ./tmp/recipe/banner.png

  # Move server_template.cfg to server.cfg
  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/logo.png
    dest: ./logo.png

  - action: move_path
    src: ./tmp/recipe/banner.png
    dest: ./banner.png

  # Connect to database
  - action: connect_database
    host: "{{dbHost}}"
    port: 3306
    username: "{{dbUsername}}"
    password: "{{dbPassword}}"
    database: "{{dbName}}"

  # Replace placeholders in server.cfg
  - action: file
    path: ./server.cfg
    replace:
      - "replace: {{serverName}}"
        with: "{{serverName}}"
      - "replace: {{dbHost}}"
        with: "{{dbHost}}"
      - "replace: {{dbName}}"
        with: "{{dbName}}"
      - "replace: {{dbUsername}}"
        with: "{{dbUsername}}"
      - "replace: {{dbPassword}}"
        with: "{{dbPassword}}"
      - "replace: {{maxClients}}"
        with: "{{maxClients}}"
      - "replace: {{svLicense}}"
        with: "{{svLicense}}"
      - "replace: {{recipeName}}"
        with: "Ricis Dev Server"
      - "replace: {{recipeDescription}}"
        with: "Recipe for Ricis custom FiveM server"

  # Additional resources
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  # Cleanup
  - action: remove_path
    path: ./tmp
